name: Pipeline tests

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    # - name: Install dependencies
    #   run: npm ci
    - name: Setup and run linter
      working-directory: ./warehouse
      run: |
        npm ci
        npm run lint
    # - run: npm run build --if-present
    # - run: npm test